project:
  name: python-skeleton
  title: Python Skeleton
  url: https://bitbucket.org/ack/python-skeleton
  download-url: https://bitbucket.org/ack/python-skeleton/downloads
  doc-url: http://python-skeleton.readthedocs.org/
  issues-url: https://bitbucket.org/ack/python-skeleton/issues

author:
  name: Alberto Donato
  email: alberto.donato@gmail.com
