requires = [ "tox>=4.6" ]

[env_run_base]
runner = "uv-venv-lock-runner"
package = "editable"
commands = [ [ "python-skeleton", { replace = "posargs", default = [], extend = true } ] ]

[env.check]
dependency_groups = [ "dev" ]
commands = [ [ "ty", "check", "python_skeleton", { replace = "posargs", default = [], extend = true } ] ]

[env.lint]
package = "skip"
dependency_groups = [ "dev" ]
commands = [ [ "pre-commit", "run", "--all-files" ] ]
